<a href="https://colab.research.google.com/github/tiwarineha16/MLProjects/blob/main/Sentence_Embedding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install transformers

In [ ]:
import torch

In [ ]:
from transformers import BertTokenizer, BertModel

In [ ]:
import random


In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
random_seed=45
random.seed(random_seed)

In [ ]:
if torch.cuda.is_available():
  torch.cuda.manual_seed_all(random_seed)

In [ ]:
tokenizer=BertTokenizer.from_pretrained("bert-base-uncased")

In [ ]:
model=BertModel.from_pretrained("bert-base-uncased")

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

In [ ]:
model

BertModel(
  (embeddings): BertEmbeddings(
    (word_embeddings): Embedding(30522, 768, padding_idx=0)
    (position_embeddings): Embedding(512, 768)
    (token_type_embeddings): Embedding(2, 768)
    (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (encoder): BertEncoder(
    (layer): ModuleList(
      (0-11): 12 x BertLayer(
        (attention): BertAttention(
          (self): BertSdpaSelfAttention(
            (query): Linear(in_features=768, out_features=768, bias=True)
            (key): Linear(in_features=768, out_features=768, bias=True)
            (value): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (output): BertSelfOutput(
            (dense): Linear(in_features=768, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False

In [ ]:
text="I work as a Data Scientist in IQVIA."
text2="I earn good salary and happy with my job."

In [ ]:
encoding = tokenizer.batch_encode_plus([text,text2],padding=True, truncation=True, return_tensors="pt",add_special_tokens=True)

In [ ]:
input_ids=encoding["input_ids"]

In [ ]:
input_ids

tensor([[  101,  1045,  2147,  2004,  1037,  2951,  7155,  1999, 26264,  9035,
          1012,   102],
        [  101,  1045,  7796,  2204, 10300,  1998,  3407,  2007,  2026,  3105,
          1012,   102]])

In [ ]:
attention_mask=encoding["attention_mask"]

In [ ]:
attention_mask

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [ ]:
with torch.no_grad():
  outputs=model(input_ids,attention_mask=attention_mask)
  word_embeddings=outputs.last_hidden_state


In [ ]:
word_embeddings.shape

torch.Size([2, 12, 768])

In [ ]:
word_embeddings

tensor([[[ 0.1187,  0.2081,  0.0636,  ..., -0.4294,  0.3036,  0.3576],
         [ 0.7722, -0.0151, -0.3140,  ..., -0.2869,  0.5935,  0.2324],
         [ 0.7721,  0.4835,  0.3344,  ..., -0.5415,  0.3076,  0.0737],
         ...,
         [ 0.4872, -0.0018,  0.1547,  ..., -0.4544,  0.1660,  0.2166],
         [ 0.3506, -0.1447, -0.2552,  ...,  0.4393, -0.2191, -0.5543],
         [ 0.5717, -0.0400, -0.0783,  ...,  0.4393, -0.6321, -0.4512]],

        [[ 0.2249,  0.4815,  0.0511,  ..., -0.5555,  0.2430,  0.2858],
         [ 0.9698,  0.2276, -0.2520,  ..., -0.8295,  0.8272,  0.0174],
         [ 0.6817,  0.3890,  0.3765,  ..., -0.9593,  0.7502, -0.1364],
         ...,
         [ 1.0913,  0.3570,  0.2133,  ..., -0.8957,  0.0727, -0.2250],
         [ 0.6621, -0.0178, -0.1348,  ...,  0.4208, -0.1675, -0.3625],
         [ 0.5779, -0.0522,  0.2378,  ...,  0.3183, -0.0316, -0.3866]]])

In [ ]:
input_ids[0][0]

tensor(101)

In [ ]:
decode=tokenizer.decode(input_ids[0],skip_special_tokens=True)

In [ ]:
decode

'i work as a data scientist in iqvia.'

In [ ]:
decode=tokenizer.decode(input_ids[1],skip_special_tokens=True)

In [ ]:
decode

'i earn good salary and happy with my job.'